name: assignment-pipeline

on:
  push:
    branches:
      -master
  workflow_dispatch:

jobs:
  assignment-job:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.2.2
      - name: my-name
        run: echo "My name is Ebunoluwa."
      - name: my-state
        run: echo "I am from Oyo State."
      - name: my-country
        run: echo "Nigeria."
      - name: favourite-meal
        run: echo "My favourite meal is rice."
        shell: bash
      
